In [17]:
import os
import sys
from stanza.utils.conll import CoNLL
import pandas as pd
import stanza
import nltk
import re
from nltk.corpus import stopwords

In [18]:
sys.path.append('..')

from utils.preprocessing import dummy_function
dummy_function('')

Hello World

# Download

In [3]:
nltk.download('punkt')
nltk.download('stopwords')
stanza.download('en')
stanza.download('de')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\mayer\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\mayer\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.9.0.json: 392kB [00:00, 32.6MB/s]
2024-11-06 00:04:47 INFO: Downloaded file to C:\Users\mayer\stanza_resources\resources.json
2024-11-06 00:04:47 INFO: Downloading default packages for language: en (English) ...
2024-11-06 00:04:49 INFO: File exists: C:\Users\mayer\stanza_resources\en\default.zip
2024-11-06 00:04:52 INFO: Finished downloading models and saved to C:\Users\mayer\stanza_resources
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.9.0.json: 392kB [00:00, 13.1MB/s]
2024-11-06 00:04:52 INFO: Downloaded file to C:\Users\mayer\stanza_resources\resources.json
2024-11-06 00:04:52 INFO: Downloading default packages for language: de (German) ...
2024-11-06 00:04:54 INFO: File exists: C:\Users\mayer\stanza_resources\de\default.zip
2024-11-06 00:05:00 INFO: Finished downloading models and saved to C:\Users\mayer\stanza_resources

# Set Path

In [21]:
# set output paths:
output_path_conllu = os.path.normpath(os.path.join(os.getcwd(), '..', 'data', 'output.conllu'))
output_path_df = os.path.normpath(os.path.join(os.getcwd(), '..', 'data', 'df.parquet'))

#data_path = os.path.join(os.getcwd(), '../data/edos_labelled_aggregated.csv')
#output_path_conllu = "../data/output.conllu"
#output_path_df= "../data/df.parquet"

In [24]:
data_url_aggregated = "https://raw.githubusercontent.com/rewire-online/edos/main/data/edos_labelled_aggregated.csv"
df = pd.read_csv(data_url_aggregated)

In [29]:
data_url_individual_annotations = "https://raw.githubusercontent.com/rewire-online/edos/main/data/edos_labelled_individual_annotations.csv"
df_individual_annotations = pd.read_csv(data_url_individual_annotations)

In [31]:
data_url_gab = "https://raw.githubusercontent.com/rewire-online/edos/main/data/gab_1M_unlabelled.csv"
df_gab = pd.read_csv(data_url_gab)

In [33]:
data_url_reddit = "https://raw.githubusercontent.com/rewire-online/edos/main/data/reddit_1M_unlabelled.csv"
df_reddit = pd.read_csv(data_url_reddit)

In [5]:
#data_path = os.path.normpath(os.path.join(os.getcwd(), '..', 'data', 'edos_labelled_aggregated.csv'))
#data_path = os.path.join(os.getcwd(), '../data/edos_labelled_aggregated.csv')
#output_path_conllu = "../data/output.conllu"
#output_path_df= "../data/df.parquet"

# Load Data

In [34]:
# df = pd.read_csv(data_path)
df.head(5)

,rewire_id,text,label_sexist,label_category,label_vector,split
0,sexism2022_english-9609,"In Nigeria, if you rape a woman, the men rape ...",not sexist,none,none,dev
1,sexism2022_english-16993,"Then, she's a keeper. 😉",not sexist,none,none,train
2,sexism2022_english-13149,This is like the Metallica video where the poo...,not sexist,none,none,train
3,sexism2022_english-13021,woman?,not sexist,none,none,train
4,sexism2022_english-966,I bet she wished she had a gun,not sexist,none,none,dev

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   rewire_id       20000 non-null  object
 1   text            20000 non-null  object
 2   label_sexist    20000 non-null  object
 3   label_category  20000 non-null  object
 4   label_vector    20000 non-null  object
 5   split           20000 non-null  object
dtypes: object(6)
memory usage: 937.6+ KB

# Splitting df

The split is based on the predefined labels in the data.

In [38]:
def split_data(df):

    train_df = df[df['split'] == 'train']
    test_df = df[df['split'] == 'test']
    dev_df = df[df['split'] == 'dev']
    
    return train_df, dev_df, test_df

# Beispielnutzung
train_df, dev_df, test_df = split_data(df)

# Ausgabe der ersten Zeilen des Trainingsdatensatzes, Dev-Datensatzes und Testdatensatzes
print("Trainingsdaten:")
print(train_df.head())
print("\nEntwicklungsdaten (Dev):")
print(dev_df.head())
print("\nTestdaten:")
print(test_df.head())

Trainingsdaten:
                                                text  label  split
1                            Then, she's a keeper. 😉      0  train
2  This is like the Metallica video where the poo...      0  train
3                                             woman?      0  train
5  Unlicensed day care worker reportedly tells co...      0  train
6  [USER] Leg day is easy. Hot girls who wear min...      1  train

Entwicklungsdaten (Dev):
                                                 text  label split
0   In Nigeria, if you rape a woman, the men rape ...      0   dev
4                      I bet she wished she had a gun      0   dev
9   I agree with that but at the same time I know ...      1   dev
15  democrats from Minnesota (leftist muzzie shith...      1   dev
29  Texas jury sentences Jordanian immigrant to de...      0   dev

Testdaten:
                                                 text  label split
21  Fuck the niggers and the jews. Both have a his...      0  test
27  Well then good because someone has to knock he...      1  test
35  #USA #Texas #Islam #Muslims #Islamization #Sha...      0  test
38  Yes, normal women want to be dominated. Social...      1  test
44  She didn't have to be a bitch about it. She li...      1  test

# Prepare df

In [36]:
df['label_sexist'] = df['label_sexist'].map({'sexist': 1, 'not sexist': 0})
df = df[["text","label_sexist","split"]]
df.rename(columns={'label_sexist': 'label'}, inplace=True)

In [37]:
df.head(10)

                                                text  label  split
0  In Nigeria, if you rape a woman, the men rape ...      0    dev
1                            Then, she's a keeper. 😉      0  train
2  This is like the Metallica video where the poo...      0  train
3                                             woman?      0  train
4                     I bet she wished she had a gun      0    dev
5  Unlicensed day care worker reportedly tells co...      0  train
6  [USER] Leg day is easy. Hot girls who wear min...      1  train
7  I don't know if you should avoid this one or e...      0  train
8  I get a new pussy every other week or whenever...      1  train
9  I agree with that but at the same time I know ...      1    dev

# Text preprocessing

In [10]:
stop_words = set(stopwords.words('english'))
nlp_pipeline = stanza.Pipeline('en', processors='tokenize,lemma,pos')

2024-11-06 00:05:28 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES
Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.9.0.json: 392kB [00:00, 24.5MB/s]
2024-11-06 00:05:28 INFO: Downloaded file to C:\Users\mayer\stanza_resources\resources.json
2024-11-06 00:05:28 WARNING: Language en package default expects mwt, which has been added
2024-11-06 00:05:29 INFO: Loading these models for language: en (English):
=================================
| Processor | Package           |
---------------------------------
| tokenize  | combined          |
| mwt       | combined          |
| pos       | combined_charlm   |
| lemma     | combined_nocharlm |
=================================

2024-11-06 00:05:29 INFO: Using device: cpu
2024-11-06 00:05:29 INFO: Loading: tokenize
C:\Users\mayer\anaconda3\envs\sexism_detection\lib\site-packages\stanza\models\tokenization\trainer.py:82: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
2024-11-06 00:05:30 INFO: Loading: mwt
C:\Users\mayer\anaconda3\envs\sexism_detection\lib\site-packages\stanza\models\mwt\trainer.py:201: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
2024-11-06 00:05:30 INFO: Loading: pos
C:\Users\mayer\anaconda3\envs\sexism_detection\lib\site-packages\stanza\models\pos\trainer.py:139: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
C:\Users\mayer\anaconda3\envs\sexism_detection\lib\site-packages\stanza\models\common\pretrain.py:56: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data = torch.load(self.filename, lambda storage, loc: storage)
C:\Users\mayer\anaconda3\envs\sexism_detection\lib\site-packages\stanza\models\common\char_model.py:271: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(filename, lambda storage, loc: storage)
2024-11-06 00:05:31 INFO: Loading: lemma
C:\Users\mayer\anaconda3\envs\sexism_detection\lib\site-packages\stanza\models\lemma\trainer.py:239: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, lambda storage, loc: storage)
2024-11-06 00:05:31 INFO: Done loading processors!

In [11]:
data = {'text': ['I am learning data science.', 'Natural language processing is fun!']}
df_test = pd.DataFrame(data)

# df = df.head(10) 
# was used before to test
def clean_text(text):
    return re.sub(r'\[USER\]', '', text).strip()

def process_text(text):
    cleaned_text = clean_text(text)
    
    doc = nlp_pipeline(cleaned_text)
    lemmas = []
    pos_tags = []
    
    for sentence in doc.sentences:
        for word in sentence.words:
            # If I use the next line it will delete "she"
            #if word.lemma.lower() not in stop_words:
            lemmas.append(word.lemma)
            pos_tags.append(word.upos)
    
    #print(doc, lemmas, pos_tags)
    return doc, lemmas, pos_tags

docs, df['lemma'], df['pos'] = zip(*df['text'].apply(process_text))

with open(output_path_conllu, 'w', encoding='utf-8') as f:
    for doc in docs:
        CoNLL.write_doc2conll(doc, f)

# Save df and read it

In [12]:
df.to_parquet(output_path_df, index=False)
df_loaded = pd.read_parquet(output_path_df)
df_loaded.head(5)

,text,label,split,lemma,pos
0,"In Nigeria, if you rape a woman, the men rape ...",0,dev,"[in, Nigeria, ,, if, you, rape, a, woman, ,, t...","[ADP, PROPN, PUNCT, SCONJ, PRON, VERB, DET, NO..."
1,"Then, she's a keeper. 😉",0,train,"[then, ,, she, be, a, keeper, ., 😉]","[ADV, PUNCT, PRON, AUX, DET, NOUN, PUNCT, PUNCT]"
2,This is like the Metallica video where the poo...,0,train,"[this, be, like, the, Metallica, video, where,...","[PRON, AUX, ADP, DET, PROPN, NOUN, ADV, DET, A..."
3,woman?,0,train,"[woman, ?]","[NOUN, PUNCT]"
4,I bet she wished she had a gun,0,dev,"[I, bet, she, wish, she, have, a, gun]","[PRON, VERB, PRON, VERB, PRON, VERB, DET, NOUN]"

# Test Print 
Be careful, if the file is too large, your environment could crash.

In [16]:
with open(output_path_conllu, encoding="utf-8") as f:
    print(''.join(f.readlines()))

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

This warning is due to the size of the data. The codechunk worked before with the testdata.